Deepbgc
nf-core/funcscan pull request #122
Opened 2022-09-08 15:04 UTC by louperelo

deepBGC is run with .fasta input. It then runs it's own Prodigal version. But funcscan's  Prodigal-process is called anyway ... I did not figure out how to modify the huge "if" statement in funcscan.nf in order to avoid this. 
To me it looked like it should not be run, if the command is:
`nextflow run . -profile docker --run_bgc_screening true --bgc_skip_antismash true --bgc_skip_gecco true --bgc_skip_hmmsearch true --outdir results/deepbgctest --input assets/samplesheet.csv`
and either prokka or prodigal is run if:
`if ( ( params.run_arg_screening && !params.arg_skip_deeparg ) || ( params.run_amp_screening && ( !params.amp_skip_hmmsearch || !params.amp_skip_amplify || !params.amp_skip_ampir ) ) || ( params.run_bgc_screening && ( !params.amp_skip_hmmsearch || !params.bgc_skip_antismash ) ) )`

closes issue #116 
## PR checklist

- [ x] This comment contains a description of changes (with reason).
- [x ] If you've fixed a bug or added code that should be tested, add tests!
  - [ x] If you've added a new tool - have you followed the pipeline conventions in the [contribution docs](https://github.com/nf-core/funcscan/tree/master/.github/CONTRIBUTING.md)
  - [ ] If necessary, also make a PR on the nf-core/funcscan _branch_ on the [nf-core/test-datasets](https://github.com/nf-core/test-datasets) repository.
- [ x] Make sure your code lints (`nf-core lint`).
- [ x] Ensure the test suite passes (`nextflow run . -profile test,docker --outdir <OUTDIR>`).
- [ ] Usage Documentation in `docs/usage.md` is updated.
- [x ] Output Documentation in `docs/output.md` is updated.
- [ ] `CHANGELOG.md` is updated.
- [ ] `README.md` is updated (including new tool citations and authors/contributors).

2022-09-08 15:06 UTC, jfy133 commented
> But funcscan's Prodigal-process is called anyway ... I did not figure out how to modify the huge "if" statement in funcscan.nf in order to avoid this.

To avoid what exactly?

2022-09-08 15:12 UTC, louperelo commented
If I only run the bcc workflow and only use deepbgc, I don't need prodigal to run

2022-09-09 06:53 UTC, jasmezz commented
Note: If the input is not `.fasta` but `.gbk`, DeepBGC recognizes that as annotated sequences and skips its internal prodigal step. Maybe that is what we should go for. I remember the raw prodigal output not being recognized by DeepBGC, so we would need to enforce prokka if `--bgc_skip_deepbgc` is false. I can have a look later today!

2022-09-09 13:02 UTC, louperelo commented
I decided going for the `.fasta` input, because I could not really see an advantage in using the `.gbk`. 
If the default setting `--run_annotation_tool prodigal` is used, we would have to run it twice anyway to once generate the `.faa` file and in a second run the `.gbk` file (Prodigal does not have the option to emit both in one run).  Also, I tried to use the `prokka.out.gbk` as `deepARG` input but without success. Would have to still find out why that wasn't accepted by `deepBGC`. 
Therefore, just using the `.fasta` input and running the internal `prodigal` in `deepBGC` seemed to be the easiest way to get a working version.

2022-09-15 11:05 UTC, louperelo commented on modules.json
> +                    "git_sha": "eae945721d9ac32227b95350b0c6d39a00d8a14f"
```suggestion
                    "git_sha": "eae945721d9ac32227b95350b0c6d39a00d8a14f",
```

2022-09-15 11:05 UTC, louperelo commented on modules.json
> +                    "git_sha": "eae945721d9ac32227b95350b0c6d39a00d8a14f"
```suggestion
                    "git_sha": "eae945721d9ac32227b95350b0c6d39a00d8a14f",
```

2022-09-15 11:06 UTC, louperelo commented on modules.json
> +                    "git_sha": "eae945721d9ac32227b95350b0c6d39a00d8a14f"
```suggestion
                    "git_sha": "eae945721d9ac32227b95350b0c6d39a00d8a14f",
```

2022-09-15 13:19 UTC, jasmezz requested changes
Looks almost good to me. Database output should go into `databases/` and not `bgc/deepbgc/db/`.

2022-09-15 13:19 UTC, jasmezz commented on workflows/funcscan.nf
> +        ch_annotation_gbk        = Channel.empty()
```suggestion
        }   else if ( params.run_annotation_tool == "prokka") {
            PROKKA ( ch_prepped_input, [], [] )
            ch_versions              = ch_versions.mix(PROKKA.out.versions)
            ch_annotation_faa        = PROKKA.out.faa
            ch_annotation_fna        = PROKKA.out.fna
            ch_annotation_gff        = PROKKA.out.gff
        }

    } else {

        ch_annotation_faa        = Channel.empty()
        ch_annotation_fna        = Channel.empty()
        ch_annotation_gff        = Channel.empty()
```
We don't use GBK right now, so I removed those 3 lines.

2022-09-15 20:34 UTC, louperelo commented on CITATIONS.md
> +  > Hannigan, Geoffrey D, David Prihoda, Andrej Palicka, Jindrich Soukup, Ondrej Klempir, Lena Rampula, Jindrich Durcak, Michael Wurst, Jakub Kotowski, Dan Chang, Rurun Wang, Grazia Piizzi, Gergely T
I tried to stick to the format of the previous citations: first author many times is <surname, first name> and all co-authors the other way round. 
But, yes, definitely, we should review this and give it all the same format!

2022-09-27 17:53 UTC, jfy133 requested changes
Just missing the prodgial version module update I think?

2022-09-29 08:55 UTC, jfy133 commented
@nf-core-bot fix linting

2022-09-29 11:35 UTC, merged