Contig separation
nf-core/funcscan pull request #361
Opened 2024-04-10 15:04 UTC by jfy133

Adds contig separation to stop crfash of antismash/gecco if contigs under required threshold.

theoreitcally Just need to update workflow diagram and ready to go.

Only thing design wise - should we future proof and  instead set values per  workflow type, rather than just long (for BGC) vs short?

For example: what if we add another screening for something else that requires 'super long' contigs? Downside is then we indeed start getting duplication of files basically

2024-04-11 13:26 UTC, jasmezz requested changes
That's great! Only minor things/typos/suggestions.

And consider renaming `--contig_qc_lengththreshold` into `contig_qc_length`. I find it obvious that it is a threshold and would make it easier to write? ;)

2024-04-11 13:26 UTC, jasmezz commented on docs/images/funcscan_metro_workflow.png
That looks great!
- For the legend: Maybe make the gray squares a little rectangular to reflect better the "dashedness" of the gray line.
- Alignment of the lines merging into the center groups of prediction tools: Can we have the distance of the 2 lines going into hmmsearch also for the other line merges? I.e. the dotted lines should end a few pixels more above their solid line partners.

2024-04-11 13:26 UTC, jasmezz commented on docs/output.md
> +The threshold for the separation can be adjusted with `--contig_qc_lengththreshold `
```suggestion
The threshold for the separation can be adjusted with `--contig_qc_lengththreshold `.
```

2024-04-11 13:26 UTC, jasmezz commented on docs/output.md
> +  - `<samplename>_long.fasta`: FASTA file containing contigs equals or longer than the threshold set by `--contig_qc_lengththreshold` used in downstream AMP, ARG, BGC subworkflows
```suggestion
  - `<samplename>_long.fasta`: FASTA file containing contigs equal or longer than the threshold set by `--contig_qc_lengththreshold` used in downstream AMP, ARG, BGC subworkflows
```

2024-04-11 13:26 UTC, jasmezz commented on docs/usage.md
> +For example, by default BGC screening requires contigs of at least 3000bp (see `--contig_qc_lengththreshold`).
```suggestion
For example, by default BGC screening requires contigs of at least 3,000 bp (see `--contig_qc_lengththreshold`).
```

2024-04-11 13:26 UTC, jasmezz commented on nextflow_schema.json
> +            "description": "These parameters influence some simple contig quality control that occur prior screening.",
```suggestion
            "description": "These parameters influence some simple contig quality control that occur prior to screening.",
```

2024-04-11 13:26 UTC, jasmezz commented on nextflow_schema.json
> +                    "help_text": "On input, nf-core/funcscan will split unannotated input contigs into two categories based on this parameter: long, and short.\n\nFor both ARG and AMPs, both categori
```suggestion
                    "description": "The sequence length threshold at which contigs are considered 'long' (above or same as threshold) vs. 'short' (below threshold).",
                    "help_text": "nf-core/funcscan will split unannotated input contigs into two categories based on this parameter: long, and short.\n\nFor both ARG and AMPs, both categories of contigs will be screened. For BGCs, only contigs in the 'long' category will be screened.\n\nThis is due to an (approximate) 'biological' minimal that nucleotide sequences need to be to synthesise a valid BGC, as well as to speeding up pipeline runs by screening only useful contigs.\n\nFile and sample ID names in results tables will be indicated by `_long` and `_short` suffixes.",
```

2024-04-11 13:26 UTC, jasmezz commented on nextflow_schema.json
> +                    "default": 1e-6,
```suggestion
                    "default": 0.000001,
```

Web-editor artificat, too...

2024-04-11 13:26 UTC, jasmezz commented on nextflow_schema.json
> +                    "default": 1e-9,
```suggestion
                    "default": 0.000000001,
```

2024-04-11 13:26 UTC, jasmezz commented on workflows/funcscan.nf
> +    // speed up e.g. BGC running with BGC-compatible contig lengths only
```suggestion
    // speed up BGC workflow with BGC-compatible contig lengths only
```

2024-04-11 13:26 UTC, jasmezz commented on workflows/funcscan.nf
> +    ch_versions = ch_versions.mix(SEQKIT_SEQ_SHORT.out.versions)
```suggestion
    ch_versions = ch_versions.mix( SEQKIT_SEQ_LONG.out.versions )
    ch_versions = ch_versions.mix( SEQKIT_SEQ_SHORT.out.versions )
```

2024-04-11 13:32 UTC, jfy133 commented
> And consider renaming `--contig_qc_lengththreshold` into `contig_qc_length`. I find it obvious that it is a threshold and would make it easier to write? ;)

I had that originally but I don't think it's very descriptive to what is actually happening. I wasn't happy with threshold either but I couldn't think of a better never...

2024-04-17 06:45 UTC, jasmezz approved these changes
All comments in, all checks succeeded --> you can merge!

2024-04-17 07:26 UTC, merged