Add InterProScan to Pipeline and integrate in AMPcombi
nf-core/funcscan pull request #428
Opened 2024-12-09 15:30 UTC by Darcy220606

## PR checklist

This PR adds InterProScan to FUNCSCAN. It also integrates it into AMPcombi v2.0.1, which can parse its output as an optional flag. 

👀 👀 👀 👀 👀 👀  Still TODO once AMPcombi 2.0.1 is updated in nf-core: 
- Still needs to be tested
- Update nf-test snapshots
- Check the dynamic optional `ext.arg` 
- Many comments still need to be deleted

- [X] This comment contains a description of changes (with reason).
- [ ] If you've fixed a bug or added code that should be tested, add tests!
- [x] If you've added a new tool - have you followed the pipeline conventions in the [contribution docs](https://github.com/nf-core/funcscan/tree/master/.github/CONTRIBUTING.md)
- [ ] If necessary, also make a PR on the nf-core/funcscan _branch_ on the [nf-core/test-datasets](https://github.com/nf-core/test-datasets) repository.
- [ ] Make sure your code lints (`nf-core lint`).
- [ ] Ensure the test suite passes (`nextflow run . -profile test,docker --outdir <OUTDIR>`).
- [ ] Check for unexpected warnings in debug mode (`nextflow run . -profile debug,test,docker --outdir <OUTDIR>`).
- [x] Usage Documentation in `docs/usage.md` is updated.
- [x] Output Documentation in `docs/output.md` is updated.
- [x] `CHANGELOG.md` is updated.
- [ ] `README.md` is updated (including new tool citations and authors/contributors).

2025-01-08 07:30 UTC, Darcy220606 commented
@nf-core-bot fix linting

2025-01-09 12:07 UTC, Darcy220606 commented
@nf-core-bot fix linting

2025-01-09 12:30 UTC, Darcy220606 commented
@nf-core-bot fix linting

2025-01-09 13:36 UTC, Darcy220606 commented
Also fixes issue number #434

2025-01-10 12:59 UTC, jfy133 reviewed
Main issue is I don't like the use of `function`, we already use `functon` in `funcscan` in  a broad sense... can you refine what exactly we are using interproscan for and then we can adjust the naming

2025-01-10 12:59 UTC, jfy133 commented on CHANGELOG.md
> +- [#428](https://github.com/nf-core/funcscan/pull/XXX) Added InterProScan annotation workflow to the pipeline. The results are coupled to AMPcombi final table. (by @darcy220606)
```suggestion
- [#428](https://github.com/nf-core/funcscan/pull/428) Added InterProScan annotation workflow to the pipeline. The results are coupled to AMPcombi final table. (by @darcy220606)
```

2025-01-10 12:59 UTC, jfy133 commented on conf/base.config
> +        time   = { 4.h * task.attempt } // Download might take longer with some Bandwidth!
```suggestion
        time   = { 4.h * task.attempt }
```

2025-01-10 12:59 UTC, jfy133 commented on conf/modules.config
> +        ext.prefix = { "${meta.id}_interproscan.faa" }
Is this meant to have the file suffix at the end?

2025-01-10 12:59 UTC, jfy133 commented on conf/modules.config
> +            path: { "${params.outdir}/databases/" },
```suggestion
            path: { "${params.outdir}/databases/ampcombi" },
```

If we use the interproscan example above?

2025-01-10 12:59 UTC, jfy133 commented on docs/output.md
> +├── function/
What exactly do you mean here by function? I don't find that particularly descriptive and would'nt know what you mean by that necessarily.

2025-01-10 12:59 UTC, jfy133 commented on docs/output.md
> +### Functional classifications
What about 'domainprediction' or something like that?

2025-01-10 12:59 UTC, jfy133 commented on docs/output.md
> +  - `<samplename>_cleaned.faa`: clean version of the fasta files (amino acids) generated by one of the annotated tools. These contain sequences with no special character
```suggestion
  - `<samplename>_cleaned.faa`: clean version of the fasta files (amino acids) generated by one of the annotated tools. These contain sequences with no special character.
```

What is an 'annotated tool'? Is this  atool within interproscan?
What is a special character?

2025-01-10 12:59 UTC, jfy133 commented on docs/output.md
> +[InterProScan](https://academic.oup.com/bioinformatics/article/30/9/1236/237988?login=true) (**a**nti**m**icrobial **p**eptide **p**rediction **i**n **r**) was designed to predict the protein functio
```suggestion
[InterProScan](https://academic.oup.com/bioinformatics/article/30/9/1236/237988?login=true) is designed to predict the protein function and and provide possible domain and motif information for the coding regions. It utilizes the InterPro database that consists of multiple sister databases such as PANTHER, ProSite, Pfam, etc. More details can be found in the [documentation](https://interproscan-docs.readthedocs.io/en/latest/index.html).
```

2025-01-10 12:59 UTC, jfy133 commented on docs/usage.md
> +[InterProScan](https://github.com/ebi-pf-team/interproscan) is currently the only functional classification tool that gives a snapshot of the protein families and domains for each coding region. By r
```suggestion
[InterProScan](https://github.com/ebi-pf-team/interproscan) is currently the only functional classification tool that gives a snapshot of the protein families and domains for each coding region. By giving `--run_function_interproscan`, the [InterPro database](http://ftp.ebi.ac.uk/pub/software/unix/iprscan/5/5.67-99.0/) v5.67-99.0 is by default downloaded and prepared and the input sequences will be screened against the database. You can skip database downloading by the pipeline on each run by manually downloading and extracting the files from any [InterPro version](http://ftp.ebi.ac.uk/pub/software/unix/iprscan/5/) and giving the resulting directory path to `--??????`.
```

2025-01-10 12:59 UTC, jfy133 commented on docs/usage.md
> +[InterProScan](https://github.com/ebi-pf-team/interproscan) is currently the only functional classification tool that gives a snapshot of the protein families and domains for each coding region. By r
Please also give the rough instrucitons on how to do this manually to the end of the USAGE section in the corresponding section as we do for all other tools

2025-01-10 12:59 UTC, jfy133 commented on docs/usage.md
> +If the `run_function_interproscan` is activated, protein and domain classifications of the coding regions are generated and the output is then integrated into the `AMPcombi parsetables` resulting tab
```suggestion
If `--run_function_interproscan` is given, protein and domain classifications of the coding regions are generated and the output is then integrated into the `AMPcombi parsetables` resulting table for every sample and the complete summary files e.g., `Ampcombi_summary.tsv`.
```

2025-01-10 12:59 UTC, jfy133 commented on nextflow_schema.json
> +                    "help_text": "This allows the user to change the default InterProScan version for coding region functional annotation, which allows for the latest release usage. By default this i
```suggestion
                    "help_text": "This allows the user to change the InterProScan database version that for coding region functional annotation that the pipeline will download for you automatically if you don't supply a pre-supplied database to `--function_interproscan_db`. Changing this URL allows for the use of the latest database release. By default this is set to `http://ftp.ebi.ac.uk/pub/software/unix/iprscan/5/5.67-99.0/interproscan-5.67-99.0-64-bit.tar.gz`. ",
```

2025-01-10 12:59 UTC, jfy133 commented on nextflow_schema.json
> +                    "help_text": "Use this to supply the path to a pre- downloaded InterProScan database. This can be any unziped InterProScan version. By default the database version '5.67-99.0' is
```suggestion
                    "help_text": "Use this to supply the path to a pre-downloaded InterProScan database. This can be any unzipped InterProScan version. By default the database version '5.67-99.0' is downloaded. \n\nFor more details on where to find different InterProScan databases see tool [documentation](https://interproscan-docs.readthedocs.io/en/latest/UserDocs.html#obtaining-a-copy-of-interproscan).\n",
```

2025-01-10 12:59 UTC, jfy133 commented on nextflow_schema.json
> +                    "help_text": "Assigns the database /s to be used to annotate the coding regions annotated during the 'ANNOTATION' workflow of the pipeline. By default these include `PANTHER,ProSi
```suggestion
                    "help_text": "A comma separated string specifying the database(s) to be used to annotate the coding regions annotated during the 'ANNOTATION' workflow of the pipeline. By default these include `PANTHER,ProSiteProfiles,ProSitePatterns,Pfam`.  \n- PANTHER (Protein ANalysis THrough Evolutionary Relationships): genes classified by their functions, using published scientific experimental evidence and evolutionary relationships. \n- PROSITE: protein domains, families, functional sites and specific patterns and profiles to identify them. \n- PFAM: protein families, represented by multiple sequence alignments and hidden Markov models (HMMs). \n\nThese databases were chosen based on the AMP workflow and therefore, with only these databases, do we guarantee the integration of the results to the AMPcombi final summary. \n\nNOTE: Currently, no integration of the results are implemented for the BGC and the ARG final summary tables. \n\nFor more information about all possible databases see the tool [documentation](https://interproscan-docs.readthedocs.io/en/latest/HowToRun.html).\n\n> Modifies tool parameter(s):\n> - InterProScan: `--applications`",
```

2025-01-10 12:59 UTC, jfy133 commented on nextflow_schema.json
> +                    "help_text": "This decreases the speed of functional annotation with InterProScan by pre-calculating matches found in the UniProtKB, thereby identifying unique matches in the quer
Do you mean decreases the speed or increasing? I assume it increases the speed if it's skipping a calculation step?

2025-01-10 12:59 UTC, jfy133 commented on nextflow_schema.json
> +                    "help_text": "This removes the residue annotation from the final XML and JSON output files, which we do not supply as output files from InerProScan. This is by default turned OFF.
```suggestion
                    "help_text": "Activating this flag  will remove the residue annotation from the final XML and JSON output files, which we do not supply as output files from InerProScan. \n\nFor more information about this flag see the tool [documentation](https://interproscan-docs.readthedocs.io/en/latest/HowToRun.html).\n\n> Modifies tool parameter(s):\n> - InterProScan: `--disable-residue-annot`",
```

2025-01-10 12:59 UTC, jfy133 commented on nextflow_schema.json
> +                    "help_text": "This disables the addition of the annotations assigned according to the databases activated to the final `<sample>_interproscan.tsv` file.  Turning this ON will remo
```suggestion
                    "help_text": "This disables the addition of the annotations assigned according to the databases activated to the final `<sample>_interproscan.tsv` file.  Turning this on will remove the annotations from the final table. It is not recommended to use this option, as it likely will cause a run failure because xxxxxxxxxxxxxxxxxxx. \n\nFor more information about this flag see the tool [documentation](https://interproscan-docs.readthedocs.io/en/latest/HowToRun.html).\n\n> Modifies tool parameter(s):\n> - InterProScan: `--enable-tsv-residue-annot`\n",
```

2025-01-10 12:59 UTC, jfy133 commented on subworkflows/local/amp.nf
> +        log.warn("[nf-core/funcscan] AMPCOMBI2: ${ch_summary_count} file passed. Skipping AMPCOMBI2_COMPLETE, AMPCOMBI2_CLUSTER, and TAXONOMY MERGING steps.")
```suggestion
        log.warn("[nf-core/funcscan] AMPCOMBI2: ${ch_summary_count} file(s) passed. Skipping AMPCOMBI2_COMPLETE, AMPCOMBI2_CLUSTER, and TAXONOMY MERGING steps.")
```

2025-01-10 12:59 UTC, jfy133 commented on subworkflows/local/amp.nf
> +        log.warn("[nf-core/funcscan] AMPCOMBI2: ${ch_summary_count} file passed. Skipping AMPCOMBI2_COMPLETE, AMPCOMBI2_CLUSTER, and TAXONOMY MERGING steps.")
It might be good (if not already) to describe in the output file that in some cases you may not get these output files if XYZ

2025-01-10 12:59 UTC, jfy133 commented on subworkflows/local/function.nf
> +    INTERPROSCAN( ch_faa_for_interproscan, ch_interproscan_db )
Missing versions mixing for interproscan

2025-01-10 12:59 UTC, jfy133 commented on subworkflows/local/function.nf
> +    // Current INTERPROSCAN version 5.59_91.0 only includes 13 columns and not 15 which ampcombi expects, so we added them here
What happens if INTERPROSCAN output changes :eyes: this scares me slightly to hardcode this but I'm not familiar with either tool

2025-01-10 12:59 UTC, jfy133 commented on workflows/funcscan.nf
> +                log.warn("[nf-core/funcscan] Functional annotation with INTERPROSCAN produced an empty TSV file. Passing empty file for ${meta.id}.")
What does 'Passin'g mean here? Skipping?

2025-01-17 10:14 UTC, Darcy220606 commented on conf/modules.config
> +        ext.prefix = { "${meta.id}_interproscan.faa" }
Yes, other wise we will have conflicting names in the work dir with suffix `*.interproscan.tsv` and because ampcombi recognises atm files with '*.faa.tsv'

2025-01-17 10:45 UTC, Darcy220606 commented on subworkflows/local/function.nf
> +    // Current INTERPROSCAN version 5.59_91.0 only includes 13 columns and not 15 which ampcombi expects, so we added them here
If its updated the following chunk for column manipulation should be removed. Hence why i would keep that comment here for future bug fixing :)

2025-01-17 10:51 UTC, Darcy220606 commented on workflows/funcscan.nf
> +                log.warn("[nf-core/funcscan] Functional annotation with INTERPROSCAN produced an empty TSV file. Passing empty file for ${meta.id}.")
is it better now?

2025-01-17 10:53 UTC, Darcy220606 commented on docs/output.md
> +### Functional classifications
We went for 'protein annotation' instead at the end.

2025-01-17 10:57 UTC, Darcy220606 commented on docs/output.md
> +  - `<samplename>_cleaned.faa`: clean version of the fasta files (amino acids) generated by one of the annotated tools. These contain sequences with no special character
Ive explained it a bit more now ..

2025-01-17 10:58 UTC, Darcy220606 commented on docs/output.md
> +├── function/
We now decided for 'protein_annotation'.

2025-01-17 11:18 UTC, Darcy220606 commented on nextflow_schema.json
> +                    "help_text": "This decreases the speed of functional annotation with InterProScan by pre-calculating matches found in the UniProtKB, thereby identifying unique matches in the quer
🫢

2025-01-17 11:23 UTC, Darcy220606 commented on docs/usage.md
> +[InterProScan](https://github.com/ebi-pf-team/interproscan) is currently the only functional classification tool that gives a snapshot of the protein families and domains for each coding region. By r
done!

2025-01-22 09:16 UTC, jfy133 reviewed
Almost there!

Also missing README update

2025-01-22 09:16 UTC, jfy133 commented on CHANGELOG.md
> +- [#428](https://github.com/nf-core/funcscan/pull/428) Added InterProScan annotation workflow to the pipeline. The results are coupled to AMPcombi final table. (by @darcy220606)
```suggestion
- [#428](https://github.com/nf-core/funcscan/pull/428) Added InterProScan protein annotation workflow to the pipeline. (by @darcy220606)
```

2025-01-22 09:16 UTC, jfy133 commented on docs/output.md
> +  - `<samplename>_cleaned.faa`: clean version of the fasta files (in amino acid format) generated by one of the annotation tools (i.e. Pyrodigal, Prokka, Bakta or Prokke). These contain sequences wit
```suggestion
  - `<samplename>_cleaned.faa`: clean version of the fasta files (in amino acid format) generated by one of the annotation tools (i.e. Pyrodigal, Prokka, Bakta). These contain sequences with no special characters (for eg. '\*' or '-').
```

2025-01-22 09:16 UTC, jfy133 commented on docs/output.md
> +In some cases, when the AMP workflow is turned on, only summary files per sample will be created in the output folder with **NO** `Ampcombi_summary.tsv` and `Ampcombi_summary_cluster.tsv` files and h
I don't understand exactly what you're trying to say here...

Is it: You will only get Ampcombi_summary/tsv and cluster.tsv if taxonomic classification is executed?

Or is it simply, if there are no XYZ hits you will not get those files?

2025-01-22 09:16 UTC, jfy133 commented on docs/usage.md
> +[InterProScan](https://github.com/ebi-pf-team/interproscan) is currently the only protein annotation tool that gives a snapshot of the protein families and domains for each coding region. By giving `
```suggestion
[InterProScan](https://github.com/ebi-pf-team/interproscan) is currently the only protein annotation tool that gives a snapshot of the protein families and domains for each coding region.
By giving `--run_protein_annotation_interproscan`, the [InterPro database](http://ftp.ebi.ac.uk/pub/software/unix/iprscan/5/5.67-99.0/) v5.67-99.0 is by default downloaded and prepared and the input sequences will be screened against the database.
You can skip database downloading by the pipeline on each run by manually downloading and extracting the files from any [InterPro version](http://ftp.ebi.ac.uk/pub/software/unix/iprscan/5/) and giving the resulting directory path to `--protein_annotation_interproscan_db`.
```
One sentence per line please (makes suggestions on diffs  MUCH easier)

2025-01-22 09:16 UTC, jfy133 commented on docs/usage.md
> +- In some cases, when the AMP workflow is turned on, only the summary files per sample will be created in the output folder with **NO** `Ampcombi_summary.tsv` and `Ampcombi_summary_cluster.tsv` files
Same as above, so make sure to copy updated description there

2025-01-22 09:16 UTC, jfy133 commented on docs/usage.md
> +A diifferent version of the database can be supplied to teh pipeline ba passing the InterProScan database directory to `--protein_annotation_interproscan_db path/to/interproscan_db/`. The directory c
```suggestion
A diifferent version of the database can be supplied to the pipeline by passing the InterProScan database directory to `--protein_annotation_interproscan_db path/to/interproscan_db/`. The directory can be created following with:
```

do you have a spellchecking extension in your VSCode? Can recommend one if not

2025-01-22 09:16 UTC, jfy133 commented on docs/usage.md
> +
```suggestion
```

Please also give what files or directory names are expected in the top level of the directory - this helps with making sure a user gives exactly the right directory (in case of nested folders from downloaded archives etc)

2025-01-22 09:16 UTC, jfy133 commented on nextflow.config
> +    run_protein_annotation_interproscan                     = false
For future proofing please make sure to follow the same structure as before:

As this`run_proteinannotation` and then have another parameter `--proteinannotation_tools`, like for tax classiciation

2025-02-02 14:02 UTC, Darcy220606 commented on docs/output.md
> +In some cases, when the AMP workflow is turned on, only summary files per sample will be created in the output folder with **NO** `Ampcombi_summary.tsv` and `Ampcombi_summary_cluster.tsv` files and h
exactly your last interpretation :)

2025-02-02 14:06 UTC, Darcy220606 commented on docs/output.md
> +In some cases, when the AMP workflow is turned on, only summary files per sample will be created in the output folder with **NO** `Ampcombi_summary.tsv` and `Ampcombi_summary_cluster.tsv` files and h
I rephrased it a bit

2025-02-02 14:14 UTC, Darcy220606 commented on docs/usage.md
> +A diifferent version of the database can be supplied to teh pipeline ba passing the InterProScan database directory to `--protein_annotation_interproscan_db path/to/interproscan_db/`. The directory c
i have one, but its overwhelmed by the amount of new words in the doc :)

2025-02-02 14:17 UTC, Darcy220606 commented on docs/usage.md
> +
Its exactly teh untarred directory as mentioed above in `--protein_annotation_interproscan_db path/to/downloaded-untarred-interproscan_db-dir/`

2025-02-02 14:19 UTC, Darcy220606 commented on nextflow.config
> +    run_protein_annotation_interproscan                     = false
Shall Imodify it now or once we add another annotation workflow in the pipeline?

2025-02-02 15:49 UTC, jfy133 commented on nextflow.config
> +    run_protein_annotation_interproscan                     = false
Do it now, as otherwise it'll cause breaking changes for the users in the future

2025-02-02 17:33 UTC, Darcy220606 commented on nextflow.config
> +    run_protein_annotation_interproscan                     = false
Done :)

2025-02-04 15:42 UTC, jasmezz requested changes
Great work overall :muscle:

Now that you introduce the `protein_annotation` workflow, I wonder if we should rename the DNA-level `annotation` workflow (of pyrodigal, bakta etc.). Maybe to `contig_annotation`, `cds_annotation`, or `orf_annotation`?

2025-02-04 15:42 UTC, jasmezz commented on nextflow_schema.json
> +                    "help_text": "A comma separated string specifying the database(s) to be used to annotate the coding regions annotated during the 'ANNOTATION' workflow of the pipeline. By default
```suggestion
                    "help_text": "A comma-separated string specifying the database(s) to be used to annotate the coding regions annotated during the contig annotation workflow of the pipeline. By default these include `PANTHER,ProSiteProfiles,ProSitePatterns,Pfam`.\n- PANTHER (Protein ANalysis THrough Evolutionary Relationships): genes classified by their functions, using published scientific experimental evidence and evolutionary relationships.\n- PROSITE: protein domains, families, functional sites and specific patterns and profiles to identify them.\n- PFAM: protein families, represented by multiple sequence alignments and hidden Markov models (HMMs).\n\nThese databases were chosen based on the AMP workflow and therefore, with only these databases, do we guarantee the integration of the results to the AMPcombi final summary.\n\nNOTE: Currently, no integration of the results are implemented for the BGC and the ARG final summary tables.\n\nFor more information about all possible databases see the tool [documentation](https://interproscan-docs.readthedocs.io/en/latest/HowToRun.html).\n\n> Modifies tool parameter(s):\n> - InterProScan: `--applications`",
```

2025-02-04 15:42 UTC, jasmezz commented on nextflow_schema.json
> +                    "description": "Assigns the database /s to be used to annotate the coding regions."
```suggestion
                    "description": "Assigns the database(s) to be used to annotate the coding regions.",
                    "fa_icon": "fas fa-database"
```

2025-02-04 15:42 UTC, jasmezz commented on nextflow_schema.json
> +                    "description": "Pre-calculates residue mutual matches."
```suggestion
                    "help_text": "This increases the speed of functional annotation with InterProScan by pre-calculating matches found in the UniProtKB, thereby identifying unique matches in the query sequences for faster annotation. By default this is turned off.\n\nFor more information about this flag see the tool [documentation](https://interproscan-docs.readthedocs.io/en/latest/HowToRun.html).\n\n> Modifies tool parameter(s):\n> - InterProScan: `---diasable-precalc`",
                    "description": "Pre-calculates residue mutual matches.",
                    "fa_icon": "fas fa-clock-rotate-left"
```

2025-02-04 15:42 UTC, jasmezz commented on nextflow_schema.json
> +                    "help_text": "This disables the addition of the annotations assigned according to the databases activated to the final `<sample>_interproscan.tsv` file.  Turning this on will remo
```suggestion
                    "help_text": "This disables the addition of the annotations assigned according to the databases activated to the final `<sample>_interproscan.tsv` file. Turning this on will remove the annotations from the final table. It is not recommended to use this option, as it will cause a run failure because the format of the resulting files will no longer be adequate for integration in the final summary tables. Currently, only applicable for AMPcombi2. \n\nFor more information about this flag see the tool [documentation](https://interproscan-docs.readthedocs.io/en/latest/HowToRun.html).\n\n> Modifies tool parameter(s):\n> - InterProScan: `--enable-tsv-residue-annot`\n",
                    "fa_icon": "fas fa-eraser",
```

Do we need this parameter at all if it breaks the pipeline when changing the default?

2025-02-04 15:42 UTC, jasmezz commented on nextflow_schema.json
> +                    "description": "Enable residue annotation in XML and JSON files."
```suggestion
                "protein_annotation_interproscan_enableresidueannot": {
                    "type": "boolean",
                    "help_text": "Activating this flag will remove the residue annotation from the final XML and JSON output files, which we do not supply as output files from InterProScan.\n\nFor more information about this flag see the tool [documentation](https://interproscan-docs.readthedocs.io/en/latest/HowToRun.html).\n\n> Modifies tool parameter(s):\n> - InterProScan: `--disable-residue-annot`",
                    "description": "Enable residue annotation in XML and JSON files.",
                    "fa_icon": "fas fa-eraser"
```
Can you check if the logic is correct? Wouldn't it have to be `protein_annotation_interproscan_disableresidueannot`?

2025-02-04 15:42 UTC, jasmezz commented on subworkflows/local/amp.nf
> +        }
```suggestion
        AMPCOMBI2_PARSETABLES ( ch_input_for_ampcombi.input, ch_input_for_ampcombi.faa, ch_input_for_ampcombi.gbk, params.amp_ampcombi_db_id, params.amp_ampcombi_db, ch_input_for_ampcombi.interpro )
    } else {
        AMP_DATABASE_DOWNLOAD( params.amp_ampcombi_db_id )
        ch_versions = ch_versions.mix( AMP_DATABASE_DOWNLOAD.out.versions )
        ch_ampcombi_input_db = AMP_DATABASE_DOWNLOAD.out.db
        AMPCOMBI2_PARSETABLES ( ch_input_for_ampcombi.input, ch_input_for_ampcombi.faa, ch_input_for_ampcombi.gbk, params.amp_ampcombi_db_id, ch_ampcombi_input_db, ch_input_for_ampcombi.interpro )
    }
```

2025-02-04 15:42 UTC, jasmezz commented on subworkflows/local/protein_annotation.nf
> +            ch_versions  = ch_versions.mix( INTERPROSCAN_DATABASE.out.versions )
```suggestion
            ch_versions = ch_versions.mix( INTERPROSCAN_DATABASE.out.versions )
```

2025-02-04 15:42 UTC, jasmezz commented on subworkflows/local/protein_annotation.nf
> +        ch_versions  = ch_versions.mix( INTERPROSCAN.out.versions )
```suggestion
        ch_versions = ch_versions.mix( INTERPROSCAN.out.versions )
```

2025-02-04 15:42 UTC, jasmezz commented on subworkflows/local/protein_annotation.nf
> +        // Current INTERPROSCAN version 5.59_91.0 only includes 13 columns and not 15 which ampcombi expects, so we added them here
Isn't this something to solve upstream on AMPcombi side? :grimacing: Is ok for now I guess, but better to have this column number check done by AMPcombi instead of pipeline level.

2025-02-04 15:42 UTC, jasmezz commented on workflows/funcscan.nf
> +        )
```suggestion
        PROTEIN_ANNOTATION ( ch_input_for_protein_annotation )
```

2025-02-04 15:42 UTC, jasmezz commented on workflows/funcscan.nf
> +                log.warn("[nf-core/funcscan] Protein annotation with INTERPROSCAN produced an empty TSV file. No protein annotation will be added for ${meta.id}.")
```suggestion
                log.warn("[nf-core/funcscan] Protein annotation with InterProScan produced an empty TSV file. No protein annotation will be added for sample ${meta.id}.")
```

2025-02-06 06:06 UTC, Darcy220606 commented on conf/modules.config
> +            path: { "${params.outdir}/protein_annotation/interproscan/" },
The other annotation tools in the annotation workflow are annotating CDS which also can be proteins. I would leave the annotation workflow as is because thats the baseline annotation step of the pipeline. This annotation step is more of an accessory annotation to the pipeline if the user wants more information from diff DB and (1) its technically not correct protein_annotation because those are nnot necessary proteins and (2) the plan is that we add more to this workflow (e.g. the functional annotation of those CDS) so protein annotation will no longer be valid.

2025-02-06 06:07 UTC, Darcy220606 commented on conf/modules.config
> +            path: { "${params.outdir}/protein_annotation/interproscan/" },
The ouput im not sure if its a good idea to add it in the same folder because those are two diff workflows

2025-02-06 06:09 UTC, Darcy220606 commented on conf/modules.config
> +            params.protein_annotation_interproscan_disableresidueannottsv ? '--enable-tsv-residue-annot' : '',
U suggest the opposite i.e. change the default to disable it, then we wont get any output in the tsv ?

2025-02-06 06:20 UTC, Darcy220606 commented on docs/usage.md
> +tar -xzf interproscan_db/interproscan-5.67-99.0-64-bit.tar.gz -C interproscan_db/
Jasmin did u test it with this DB version?

2025-02-06 06:28 UTC, Darcy220606 commented on nextflow.config
> +    protein_annotation_interproscan_db_url                  = 'http://ftp.ebi.ac.uk/pub/software/unix/iprscan/5/5.67-99.0/interproscan-5.67-99.0-64-bit.tar.gz'
i would not change it to that. I developed it for that version and the ones before. Would have to test it with this to make sure all is still good.

2025-02-06 06:28 UTC, Darcy220606 commented on nextflow_schema.json
> +                    "default": "http://ftp.ebi.ac.uk/pub/software/unix/iprscan/5/5.67-99.0/interproscan-5.67-99.0-64-bit.tar.gz",
again wouldnt change the version until thats tested.

2025-02-06 06:29 UTC, Darcy220606 commented on nextflow_schema.json
> +                    "help_text": "This allows the user to change the InterProScan database version that for coding region functional annotation that the pipeline will download for you automatically i
version issue. see up

2025-02-06 06:29 UTC, Darcy220606 commented on nextflow_schema.json
> +                    "help_text": "Use this to supply the path to a pre-downloaded InterProScan database. This can be any unzipped InterProScan version. By default the database version '5.67-99.0' is
until we test the version...

2025-02-06 06:35 UTC, Darcy220606 commented on nextflow_schema.json
> +                    "description": "Enable residue annotation in XML and JSON files."
Its for other files, that we do not want to be included in teh output.

2025-02-06 06:37 UTC, Darcy220606 commented on nextflow_schema.json
> +                    "help_text": "This disables the addition of the annotations assigned according to the databases activated to the final `<sample>_interproscan.tsv` file.  Turning this on will remo
Isnt it better to include it here and say why that should noot be touched rather than the user adding it later as an `èxt.arg` ?

2025-02-06 06:43 UTC, Darcy220606 commented on subworkflows/local/protein_annotation.nf
> +        // Current INTERPROSCAN version 5.59_91.0 only includes 13 columns and not 15 which ampcombi expects, so we added them here
And thats where updating the database version is not a good idea before testing. 
AMPcombi was developed on an updated version of InterProScan to the one available as a nf-core module. So its rather updating the module on nf-core than downgrading AMPcombi.

2025-02-06 09:52 UTC, jasmezz approved these changes
I'll check if it's feasible to test the most recent interproscan db on our server in order to update it here. If not, then go ahead as is. :+1:

2025-02-06 09:52 UTC, jasmezz commented on conf/modules.config
> +            params.protein_annotation_interproscan_disableresidueannottsv ? '--enable-tsv-residue-annot' : '',
Hmm no, I changed to enable it by default, i.e. if the param is false (which is default), then activate `--enable-tsv-residue-annot`. Or am I missing some logic of this?

2025-02-06 09:52 UTC, jasmezz commented on docs/usage.md
> +tar -xzf interproscan_db/interproscan-5.67-99.0-64-bit.tar.gz -C interproscan_db/
No, I didn't. But you're right, then I will download it to our server and test it; would be nice to have a more recent version towards the pipeline release.

2025-02-06 09:52 UTC, jasmezz commented on nextflow_schema.json
> +                    "help_text": "This disables the addition of the annotations assigned according to the databases activated to the final `<sample>_interproscan.tsv` file.  Turning this on will remo
They cannot add it by ext.arg :D Everything that should be ext.arg is a pipeline parameter. If we don't offer it, the user cannot use it. That's why we add as much as necessary and leave out everything that shouldn't be touched (or is too irrelevant).

2025-02-06 09:52 UTC, jasmezz commented on subworkflows/local/protein_annotation.nf
> +        // Current INTERPROSCAN version 5.59_91.0 only includes 13 columns and not 15 which ampcombi expects, so we added them here
Okay! Fair point if AMPcombi is tested to work with a specific interproscan version :+1: Just need to remember to edit this code when interproscan nf-core module gets updated one day. We could do it :nerd_face:

2025-02-06 13:12 UTC, jasmezz commented on docs/usage.md
> +tar -xzf interproscan_db/interproscan-5.67-99.0-64-bit.tar.gz -C interproscan_db/
I tested the database version 5.72-103.0 and can confirm that all output files contain valid results, i.e. `results/protein_annotation/interproscan/sample_4_interproscan.faa.tsv` and `results/reports/ampcombi2/Ampcombi_summary.tsv`. In my test case they are even identical. We can go ahead with the new version, so please commit my database update comments before merge :)

2025-02-06 15:32 UTC, jasmezz requested changes
Things to do before merge:
- address the database update comments from my previous review since I tested the new interpro scan db version today (see comment [here](https://github.com/nf-core/funcscan/pull/428#discussion_r1944702400))
- either fix ampcombi/parsetables error as reported in #444 or outsource this to a different PR

2025-02-10 10:10 UTC, Darcy220606 commented on docs/usage.md
> +tar -xzf interproscan_db/interproscan-5.67-99.0-64-bit.tar.gz -C interproscan_db/
Thank you for testing. Ill upgrade the version in that case

2025-02-10 10:17 UTC, Darcy220606 commented on subworkflows/local/protein_annotation.nf
> +        // Current INTERPROSCAN version 5.59_91.0 only includes 13 columns and not 15 which ampcombi expects, so we added them here
If u want to get involved here is what they had to go through https://github.com/bioconda/bioconda-recipes/issues/21601 :)

2025-02-10 10:26 UTC, Darcy220606 commented on conf/modules.config
> +            params.protein_annotation_interproscan_disableresidueannottsv ? '--enable-tsv-residue-annot' : '',
correct - good catch 🏀 🏀 🏀

2025-02-10 10:37 UTC, Darcy220606 commented
> Things to do before merge:
> 
> * address the database update comments from my previous review since I tested the new interpro scan db version today (see comment [here](https://github.com/nf-core/funcscan/pull/428#discussion_r1944702400))
> * either fix ampcombi/parsetables error as reported in [AMP screening doesn't run when only a single tool is enabled #444](https://github.com/nf-core/funcscan/issues/444) or outsource this to a different PR

- Thank you for testing with the latest release of InterProScan. 
- With regards to this issue #444, once this PR https://github.com/nf-core/modules/pull/7458 is reviewed and merged, ampcombi2/parsetables can be updated in the pipeline in a sep. PR to solve it.

2025-02-10 14:33 UTC, jasmezz commented on nextflow_schema.json
> +                    "help_text": "Use this to supply the path to a pre-downloaded InterProScan database. This can be any unzipped InterProScan version. By default the database version '5.67-99.0' is
Since I tested the 5.72-103.0 database on our sever and it works, I would update this help text. Will add it back in my review.

2025-02-10 15:48 UTC, jasmezz approved these changes
Just a few things. I will pull the updated ampcombi module as well so we are ready to go :)

2025-02-10 15:48 UTC, jasmezz commented on nextflow_schema.json
> +                    "help_text": "Activating this flag  will remove the residue annotation from the final XML and JSON output files, which we do not supply as output files from InerProScan. \n\nFor m
```suggestion
                    "help_text": "By default, this flag removes the residue annotation from the final XML and JSON output files, which we do not supply as output files from InterProScan.\n\nFor more information about this flag see the tool [documentation](https://interproscan-docs.readthedocs.io/en/latest/HowToRun.html).\n\n> Modifies tool parameter(s):\n> - InterProScan: `--disable-residue-annot`",
```

2025-02-10 15:48 UTC, jasmezz commented on nextflow_schema.json
> +                    "help_text": "This disables the addition of the annotations assigned according to the databases activated to the final `<sample>_interproscan.tsv` file.  Turning this on will remo
We just discussed on Slack ([here](https://nfcore.slack.com/archives/C043FMKUNLB/p1739198611742959)), that it might be safer to throw a warning in the AMP workflow, if the user changes this interproscan flag. Because we shouldn't expect them to read the whole params page or give them the pipeline-supported option to switch this flag and thereby crash the pipeline :see_no_evil:

2025-02-10 15:48 UTC, jasmezz commented on nextflow_schema.json
> +                    "fa_icon": "fas fa-clock-rotate-left"
```suggestion
                    "fa_icon": "fas fa-clock"
```

2025-02-11 11:30 UTC, merged